### ISSUE TITLE
Migration tool in version 3.26 fail to build.

### ISSUE THREAD

**Issue by vmariano** [hhvm/hhast#317] opened 2020-08-09 21:02 UTC
Hello Folks.

I'm currently going on the migration of version 3.26 to 3.30, I'm trying to use the migration tool, I checked out the current version, but couldn't build dependencies by my HHVM version.

So, I tried to check out tag v3.27.4 of the tool, but when I run the composer install I got:
```
hhast git:(v3.27.4-branch) ✗ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file

Package operations: 33 installs, 0 updates, 0 removals
  
- Installing hhvm/hhvm-autoload (v1.6.6): Loading from cache
    Skipped installation of bin bin/hh-autoload for package hhvm/hhvm-autoload: name conflicts with an existing file

Fatal error: Cannot use 'HH\string' as class name as it is reserved in /opt/projects/hhast/vendor/composer/hhvm/hhvm-autoload/src/ComposerPlugin.php on line 90
```

- This is a particular bug of my version? 

- Should I use next version? 

- this tool is retro compatible?

- Can I skip versions?

**Comment by lexidor** [comment] 2020-08-09 22:26
I believe the issue is simple to resolve. When using composer to install libraries for hhvm 3.30.x and below, you must run composer with hhvm. If you are installing libraries for hhvm 4.0.0 and above, you must run composer with php.

Unless you've aliased composer to run using hhvm, you're most likely running it with php. 

`HH\string` is the internal name for `string` in hhvm and the PHP runtime does not know how to deal with that. Try running `hhvm /path/to/composer.phar` install.

If this does not resolve the issue, feel free to @lexidor me.

**Comment by vmariano** [comment] 2020-08-13 12:12
Cool it works! 

```
 hhvm /usr/local/bin/composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 33 installs, 0 updates, 0 removals
  - Installing hhvm/hhvm-autoload (v1.6.6): Loading from cache
    Skipped installation of bin bin/hh-autoload for package hhvm/hhvm-autoload: name conflicts with an existing file
  - Installing hhvm/hsl (v3.27.0): Downloading (100%)
  - Installing hhvm/type-assert (v3.2.2): Downloading (100%)
  - Installing facebook/hh-clilib (v1.1.2): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.8.0): Downloading (100%)
  - Installing symfony/yaml (v4.1.1): Downloading (100%)
...
```

Thanks for your help!

**Comment by lexidor** [comment] 2020-08-13 15:28
You're welcome, I'll close this issue.

Please check the [hhvm blog](https://hhvm.com/blog) for information on supported hhvm versions. The oldest supported version is hhvm 4.32, which is an lts release. Support for that version lasts a few more months.

You've got a major step ahead of you, since hhvm 4.xx does not execute unmodified php code anymore. If you need help with anything or advice for porting php code over to Hack code, feel free to contact me.

**Closed by lexidor** 2020-08-13 15:28 UTC
