### ISSUE TITLE
Feature request: Remove dependency on HHVM's parser

### ISSUE THREAD

**Issue by muglug** [hhvm/hhast#200] opened 2019-07-26 21:40 UTC
This whole package depends on having the exact same version as the locally-installed version of HHVM.

While that's great for ensuring everyone's up-to-date, it's a bit of a pain when trying to work a project that uses a slightly older version of this repository when you're running latest hhvm (or the other way around).

I understand it would involve a big duplication of code, but I think it would improve usability measurably - the difference between https://github.com/nikic/php-ast (with its hard engine dependencies) and https://github.com/nikic/PHP-Parser. Far more has been built on top of the latter than the former.

**Comment by fredemmott** [comment] 2019-07-26 22:01
I think this is basically a duplicate of #43; the HHVM version constraint is primarily there to constrain the version of the `hh_parse` binary used. If `hh_parse --schema` differs from what HHAST is expecting - this can't work; changing the schema changes the codegen ,which changes how the API is used.

For example, the return type of various methods changed from `AttributeSpecification` to `OldAttributeSpecification` in HHAST 4.15 as the type got renamed in Hack's AST; even if the codegen was separated, it would not possible in a type-safe fashion to write a `MustUseOverrideAttributeLinter` that works with either `hh_parse` output.

As for splitting out the grammar like php-parser does: the lex/yacc code in hphp/parser is not usable for running/analyzing modern hack code; it's just there because of some weird stuff in hphpd we've not managed to separate yet. Since roughly May 2018, the only parser capable of dealing with Hack files sufficiently is handwritten ocaml; splitting off would require fully reimplementing a new parser in Hack, not adapting an existing parser-generator to target hack instead of ocaml/C.

**Comment by muglug** [comment] 2019-07-29 14:24
> splitting off would require fully reimplementing a new parser in Hack, not adapting an existing parser-generator to target hack instead of ocaml/C.

And presumably there's no easy way to just compile the `hh_parse` portion of the HHVM engine?

I have a situation where I'm ingesting the output of `hh_parse` into PHP transpiled from the `hhvm/hhast` source code. On my local machine (where homebrew keeps me up-to-date) everything is fine, but I'm unable to find a prebuilt 4.15 image for my centos7 web server, so there's a bit of a disconnect there.

**Comment by fredemmott** [comment] 2019-07-29 16:23
`make hack` is a little bit more than that, but shouldn't be too bad
you can also edit `hphp/hack/src/Makefile.dune` to remove references to binaries other than `hh_parse`, then run `make hack`; do not replace any of the other binaries (especially not `hh_single_compile`) or HHVM will be broken.

The main problem with this approach is distribution as it's native executables, and it's not a "grab any recent compiler and `$COMPILER foo.ml`" situation - so 'grab the source and build it yourself' is not a practical option except for people already familiar with ocaml/opam workflows. This /might/ improve in the near future with work to rewrite the parser in Rust, but that's not a goal of the rewrite.

I understand this doesn't solve it generally, but if you're familiar with centos native packaging, I'd be happy to review a pull request for https://github.com/hhvm/packaging - main requirement is to use distribution's best practices, not e.g. checkinstall or manually poking with cpio/tar/ar.

In the other direction, if you have 4.(>=3) on your centos machine, you can now `brew install hhvm-4.x` (after `brew unlink hhvm-4.15`) to get a matching version, then use an older HHAST that is compatible with that hh_parse.

Closing as:
- we don't currently have a way to specify a dependency on hh_parse instead of HHVM
- I don't think this  - over #43 - would benefit a sufficient amount of users to be a good use of time

**Closed by fredemmott** 2019-07-29 16:23 UTC
