### ISSUE TITLE
Unused local variable linter false positive

### ISSUE THREAD

**Issue by lexidor** [hhvm/hhast#208] opened 2019-08-29 18:43 UTC
```HACK
$xxx = (inout vec<int> $p) ==> {
  $p[] = 1;
};
```
UnusedVariable: Variable is unusedHHAST(UnusedVariable) for $p.

**Comment by ryangreenberg** [comment] 2019-08-29 21:46
Thanks for flagging this, @lexidor. This is _supposed_ to be handled by the portion of the linter that considers pass-by-reference or inout parameters always used, so the bug is likely related to this https://github.com/hhvm/hhast/blob/f03fc0d74b0349cf39e26836de30529ad8934e3c/src/Linters/UnusedVariableLinter.hack#L60

**Comment by ryangreenberg** [comment] 2019-08-29 22:01
I added a failing test for this at https://github.com/ryangreenberg/hhast/commit/b3db90538cc4a45c565f7770ec8cde359a061073 :

```Hack
<?hh function foo() { return (inout vec<int> $p) ==> { $p[] = 1; }; }
```

which gives the output you have here:

```
vendor/bin/hacktest.hack tests/UnusedVariableLinterTest.hack 
.................E.................

1) Facebook\HHAST\UnusedVariableLinterTest::testCleanExample[13]
Expected no errors, got:
- Facebook\HHAST\UnusedVariableLinter: Variable is unused at line 55:
$p

Summary: 35 test(s), 34 passed, 0 failed, 0 skipped, 1 error(s).
```

The problem is in getAlwaysUsedVariables because it is evaluating whether $p is inout in the context of the function `foo`, not in the context of the lambda expression. I think this points to a larger class of bugs where variables inside a lambda expression are co-mingled with variables inside the rest of the function. It's not immediately obvious to me how to approach a fix for this.

**Comment by jjergus** [comment] 2019-08-30 00:28
I suppose false negatives would be preferable over false positives, so maybe we could do something simple like ignore all variables that are `inout` in the parent function and/or any lambda inside that function?

**Comment by ryangreenberg** [comment] 2019-08-30 17:05
@jjergus Yeah, I think that's reasonable.

**Closed** 2019-08-30 18:10 UTC
